### PR TITLE
Update: Updated from 0.12.8 -> terraform 0.14.0

### PR DESCRIPTION
**Pull request by mckadesorensen**

### CODE REVIEW

**Comment by lindsleycj** [comment]
Probably should have made my comment here rather that in CIRRUS-DAAC.  So, I'll copy it here:

@mckadesorensen Is there a particular reason you are wanting this upgrade? The Cumulus documentation has been updated to a later release in the 0.12.* family and I could definitely support using that release.

https://nasa.github.io/cumulus/docs/deployment/deployment-readme

However I'd be cautious about going to 0.14.* (especially a x.x.0 release) without concurrence from the Cumulus team. I'd also want @michaeljb to weigh in.

Have you been able to test a full deployment with this release of terraform?

**Comment by mckadesorensen** [comment]
> Probably should have made my comment here rather that in CIRRUS-DAAC. So, I'll copy it here:
> 
> @mckadesorensen Is there a particular reason you are wanting this upgrade? The Cumulus documentation has been updated to a later release in the 0.12.* family and I could definitely support using that release.
> 
> https://nasa.github.io/cumulus/docs/deployment/deployment-readme
> 
> However I'd be cautious about going to 0.14.* (especially a x.x.0 release) without concurrence from the Cumulus team. I'd also want @michaeljb to weigh in.
> 
> Have you been able to test a full deployment with this release of terraform?

I was having issues deploying with version 0.12.*. I kept getting an error. Although my issue might have been something else. I am going to try and deploy it again, there is a possible chance when I was having the issues, I was on an older branch containing an older version.

**Comment by mckadesorensen** [comment]
Also, I have deployed it succesfully with the newer version but I would rather stick with the version cumulus uses if it works.

**Comment by lindsleycj** [comment]
If you've deployed with 0.14.0, I doubt you'll be able to revert to 0.12.x.  I hope I'm wrong, but I don't think so.

**Pull request closed without merging**
