### PR TITLE
PR-6041 Update Cumulus to v18.3.3

### PR DESCRIPTION
**Pull request by reweeden**

### CODE REVIEW

**Review by gjclark — APPROVED** [review]

**Review by lindsleycj — APPROVED** [review]
Looks very straight forward.  Good by me

**Comment by mckadesorensen** [comment]
Need to update the elasticsearch_config https://github.com/nasa/cumulus/releases/tag/v18.3.2

**Comment by mckadesorensen** [comment]
https://github.com/asfadmin/CIRRUS-core/blob/588a28e67f0cf2cab0bd1106c869239607ba6a17/data-persistence/variables.tf#L23

**Review by gjclark — APPROVED** [review]

**Comment by reweeden** [comment]
That needs to be added to DAAC. I have a draft PR for it: https://github.com/asfadmin/CIRRUS-DAAC/pull/116

**Review by mattp0 — APPROVED** [review]

**Review by mckadesorensen — APPROVED** [review]

**Pull request merged**
