### PR TITLE
upgrade to Cumulus v10.1.2

### PR DESCRIPTION
**Pull request by michaeljb**
Related: https://github.com/asfadmin/CIRRUS-DAAC/pull/65

### CODE REVIEW

**Review by mckadesorensen — APPROVED** [review]

**Comment by lindsleycj** [comment]
Hi, Michael, thanks for updating the PR.  I will try deploying this release.

**Comment by lindsleycj** [comment]
@michaeljb What do you think of also upgrading TEA to the latest release https://github.com/asfadmin/thin-egress-app/releases/tag/tea-release.1.0.1 - they are now using semantic versioning.

**Comment by michaeljb** [comment]
> @michaeljb What do you think of also upgrading TEA to the latest release https://github.com/asfadmin/thin-egress-app/releases/tag/tea-release.1.0.1 - they are now using semantic versioning.

@lindsleycj sounds great!

**Comment by michaeljb** [comment]
@lindsleycj hmm in a quick test with my browser, I can still access https://s3.amazonaws.com/asf.public.code/thin-egress-app/tea-terraform-build.121.zip (the URL currently used in `cumulus/thin-egress.tf`) but cannot access s3::https://s3.amazonaws.com/asf.public.code/thin-egress-app/tea-terraform-build.1.0.1.zip -- do you know if the new build is in a different location?

**Comment by lindsleycj** [comment]
@michaeljb I posted a question in the #tea-pot slack channel to see if my guess is right.

**Comment by lindsleycj** [comment]
@michaeljb I made a small change to the data-migration1.sh script to use the payload mentioned in the 10.1.1 migration instructions:  

```
# run this lambda after deploying the data-persistence module and before deploying the cumulus module

PAYLOAD=$(echo '{"forceRulesMigration": true}')

aws lambda invoke --function-name $DEPLOY_NAME-cumulus-$MATURITY-data-migration1 \
  --payload "$PAYLOAD" $DEPLOY_NAME-cumulus-$MATURITY-dm1.log
```

If you agree with this change, I can push it to your branch.

**Comment by michaeljb** [comment]
Ah good catch, thanks @lindsleycj! Yes, please do push it 🙂

**Comment by lindsleycj** [comment]
@michaeljb Done.  Also upgraded TEA.  I'm still working on my workflow updates.  As soon as I have them working, I'll merge this request.

**Comment by michaeljb** [comment]
@lindsleycj fantastic, thank you!

**Comment by lindsleycj** [comment]
I successfully installed this to my sandbox install and ran a sample ingest it looked good.  I'm going to merge

**Pull request merged**
