### PR TITLE
V14.1.0.1 rc

### PR DESCRIPTION
**Pull request by lindsleycj**
Upgrade TEA to v1.3.2 add changelog entries.

### CODE REVIEW

**Review by mikedorfman — APPROVED** [review]
Looks great to me!

**Comment by lindsleycj** [comment]
@reweeden Cumulus has supported an s3credentials endpoint for quite a long time.  Here is ORNL's for example:

https://data.ornldaac.earthdata.nasa.gov/s3credentials

Is the TEA version different somehow?

**Comment by lindsleycj** [comment]
@reweeden I made another commit to expose the s3 credentials variable and update the CHANGELOG to point to your documentation.  Would you like to see any other changes?

**Comment by lindsleycj** [comment]
Sounds good.  I'm going to merge and create a new release

**Pull request merged**
