### PR TITLE
Cumulus v4.0.0

### PR DESCRIPTION
**Pull request by mckadesorensen**

### CODE REVIEW

**Review by benbart — APPROVED** [review]

**Comment by lindsleycj** [comment]
Hi,  there are some more changes needed.  Let me see if I can get them into this branch for your review

**Comment by lindsleycj** [comment]
I had an issue deploying TEA build 100 within the Cumulus framework.  I found a workaround by using a two step hack.  But, I'm not sure we want to make all Cumulus users do that.  The Cumulus folks have created a Jira issue to resolve it:

https://bugs.earthdata.nasa.gov/browse/CUMULUS-2258

Are you all on EOSDIS Slack.  The issue I had and my workround are in the `#cumulus-internal` channel yesterday.  If your not on Slack I can post the exchange here.

**Comment by mckadesorensen** [comment]
We are all on EOSDIS Slack, I am currently reading the exchange. I am fine with sticking with 88 but I haven't tested it to make sure it works with Cumulus v4.0.0. I can do that real quick.

**Comment by lindsleycj** [comment]
Did you not have the issue upgrading to build 100?  Maybe I did something wrong.

**Comment by mckadesorensen** [comment]
I am pretty sure I had the same issue and if I remember correctly these were the causes [link 1](https://github.com/asfadmin/CIRRUS-DAAC/blob/b58c503b70944b51f674fac50b4a9fed0ac6a122/daac/main.tf#L183) [link 2](https://github.com/asfadmin/CIRRUS-DAAC/blob/b58c503b70944b51f674fac50b4a9fed0ac6a122/daac/outputs.tf#L16). I am currently double-checking to make sure this is accurate.

**Comment by lindsleycj** [comment]
I haven't used this code to deploy to an instance of Cumulus that's integrated with Cloud Metrics.  That was an issue @michaeljb and I had when working on Cumulus 3.0.  I'm calling it a night tonight but will try to deploy this to my UAT environment tomorrow morning and make sure we still have everything in place.

**Comment by lindsleycj** [comment]
I deployed to UAT this morning and all the Cloudwatch log subscriptions for Cloud Metrics are still in place so I think we're good.  

I made one more set of updates to expose several ecs_cluster variables that would be handy for my use case.  I gave them all default values which match what we had before, so users who don't want to mess with them should see no change.

Also, personally, I have upgraded all my TEA instances to build 100.  I'm fine if you leave that version in this update.  I would just recommend a CHANGELOG entry that explains the two step upgrade process.

I'm taking off the rest of the week but will be periodically checking email and such.  I'll be slow in responding until Monday.

**Review by lindsleycj — COMMENTED** [review]
@mckadesorensen This change breaks my TEA install.  When I try to download files I get this error from the TEA Lambda:  

`{
    "reason": "ClientError",
    "s3": "ornl-cumulus-uatornl-cumulus-uat-protected/daymet/Daymet_Daily_V4/data/daymet_v4_daily_na_srad_2019.nc.dmrpp",
    "code": 404,
    "http_method": "GET",
    "status": "failure"
}`

Notice how the prefix is added to an already complete bucket name. Is there something I'm missing?

**Comment by lindsleycj** [comment]
@benbart @mckadesorensen Do you all feel comfortable merging these changes to master.  I feel it's all working for me.

**Comment by mckadesorensen** [comment]
> @benbart @mckadesorensen Do you all feel comfortable merging these changes to master. I feel it's all working for me.

I am sorry I have been terrible at responding. I have been preoccupied with another task.

**Pull request merged**
